# Generated by Django 5.0.1 on 2025-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('item_description', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('received_from', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('receiving_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Inventory',
                'ordering': ['code'],
            },
        ),
    ]
