# Generated by Django 5.0.1 on 2025-01-31 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_balance_medicine_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='item_description',
            field=models.CharField(max_length=255, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Received From'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='receiving_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Receiving Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
