# Generated by Django 5.0.1 on 2025-01-28 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicineinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='manufacturer',
            new_name='received_from',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AddField(
            model_name='medicine',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='receiving_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
