# Generated by Django 5.0.1 on 2025-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_description_medicine_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='id_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacyuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('sales', 'Sales Personnel')], default='pharmacist', max_length=20),
        ),
    ]
