# Generated by Django 5.0.1 on 2025-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_paymentmethod_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='MedicineInventory',
        ),
    ]
